export const TOKENS = Object.freeze({
  '--vs-bg': '#FFFFFF',
  '--vs-surface': '#F5F5F7',
  '--vs-surface-raised': '#FFFFFF',
  '--vs-ink': '#1D1D1F',
  '--vs-ink-dim': '#55555A',
  '--vs-ink-faint': '#C7C7CC',
  '--vs-ink-muted': '#6E6E73',
  '--vs-rule': '#E5E5EA',
  '--vs-accent': '#0062C4',
  '--vs-accent-soft': 'rgba(0,98,196,0.10)',
  '--vs-positive': '#007A52',
  '--vs-negative': '#C0341A',
  '--vs-font-display': "-apple-system, 'SF Pro Display', Inter, system-ui, sans-serif",
  '--vs-font-text': "ui-serif, 'Iowan Old Style', Palatino, Georgia, serif",
  '--vs-font-mono': "ui-monospace, 'SF Mono', Menlo, monospace",
  '--vs-hero': 'clamp(3.5rem, 9vw, 7.5rem)',
  '--vs-hero-unit': 'clamp(1rem, 1.5vw, 1.5rem)',
  '--vs-h1': 'clamp(1.75rem, 2.9vw, 2.6rem)',
  '--vs-h2': '1.375rem',
  '--vs-body': '1.0625rem',
  '--vs-small': '0.9375rem',
  '--vs-micro': '0.6875rem',
  '--vs-unit': '8px',
  '--vs-measure': '1240px',
  '--vs-gutter': 'clamp(1.5rem, 4vw, 3.5rem)',
  '--vs-chapter': 'clamp(3rem, 6vh, 5rem)',
  '--vs-radius': '12px',
  '--vs-duration': '820ms',
  '--vs-stagger': '70ms',
  '--vs-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
  '--vs-print-bg': '#FFFFFF',
  '--vs-print-ink': '#111111',
  '--vs-print-rule': '#CCCCCC',
});

export function tokensToCss(tokens = TOKENS) {
  const body = Object.entries(tokens).map(([k, v]) => `${k}:${v}`).join(';');
  return `:root{${body}}`;
}
