export const TOKENS = Object.freeze({
  '--vs-bg': '#0A0B0D',
  '--vs-surface': '#14161A',
  '--vs-surface-raised': '#1B1E24',
  '--vs-ink': '#F4F5F7',
  '--vs-ink-dim': '#9AA1AB',
  '--vs-ink-faint': '#5A616B',
  '--vs-ink-muted': '#8D949E',
  '--vs-rule': '#23272E',
  '--vs-accent': '#F5B942',
  '--vs-accent-soft': 'rgba(245,185,66,0.14)',
  '--vs-positive': '#4ADE80',
  '--vs-negative': '#FF6B5A',
  '--vs-font-display': "-apple-system, 'SF Pro Display', Inter, system-ui, sans-serif",
  '--vs-font-text': "ui-serif, 'Iowan Old Style', Palatino, Georgia, serif",
  '--vs-font-mono': "ui-monospace, 'SF Mono', Menlo, monospace",
  '--vs-hero': 'clamp(3.5rem, 9vw, 7.5rem)',
  '--vs-hero-unit': 'clamp(1rem, 1.5vw, 1.5rem)',
  '--vs-h1': 'clamp(1.75rem, 2.9vw, 2.6rem)',
  '--vs-h2': '1.375rem',
  '--vs-body': '1.0625rem',
  '--vs-small': '0.9375rem',
  '--vs-micro': '0.6875rem',
  '--vs-unit': '8px',
  '--vs-measure': '1240px',
  '--vs-gutter': 'clamp(1.5rem, 4vw, 3.5rem)',
  '--vs-chapter': 'clamp(3rem, 6vh, 5rem)',
  '--vs-radius': '12px',
  '--vs-duration': '820ms',
  '--vs-stagger': '70ms',
  '--vs-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
  '--vs-print-bg': '#FFFFFF',
  '--vs-print-ink': '#111111',
  '--vs-print-rule': '#CCCCCC',
});

export function tokensToCss(tokens = TOKENS) {
  const body = Object.entries(tokens).map(([k, v]) => `${k}:${v}`).join(';');
  return `:root{${body}}`;
}
