#!/usr/bin/env node
// Renders every demo fixture (plus the canonical example fixture) into
// examples/*.html and writes examples/index.html linking to all of them.
//
// Re-runnable and deterministic: renderCase()/deliverCase() have no clock or
// randomness, so running this script twice in a row produces byte-identical
// output. It only writes under examples/; it never touches fixtures/.
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { deliverCase } from '../src/deliver.mjs';
import { tokensToCss } from '../src/render/tokens.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const FIXTURES_DEMO = path.join(ROOT, 'fixtures', 'demo');
const FIXTURES_MAIN = path.join(ROOT, 'fixtures', 'example.value-case.json');
const OUT_DIR = path.join(ROOT, 'examples');

// One-line description of what each case is testing, keyed by fixture
// basename (without the .value-case.json suffix). Order here is display
// order in the gallery.
const DESCRIPTIONS = {
  'example': 'The canonical fixture used throughout the design spec and docs.',
  'strong-measured': 'The ideal case: several measured claims with big, clean deltas.',
  'mostly-estimated': 'One measured claim among three named-owner estimates — can a reader still tell tiers apart at a glance?',
  'qualitative-only': 'No measured or estimated claims at all — exercises the no-hero fallback path.',
  'wide-portfolio': 'A primary driver plus six secondaries — the constellation at density.',
  'long-labels': 'Deliberately long metric names, units, headlines and an owner name — the layout stress test.',
  'minimal': 'The smallest document the schema permits — does the low end look empty or intentional?',
};

function listFixtures() {
  const demoFiles = readdirSync(FIXTURES_DEMO)
    .filter((f) => f.endsWith('.value-case.json'))
    .sort()
    .map((f) => ({ id: f.replace(/\.value-case\.json$/, ''), src: path.join(FIXTURES_DEMO, f) }));
  return [
    { id: 'example', src: FIXTURES_MAIN },
    ...demoFiles,
  ];
}

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function buildIndex(entries) {
  const styles = `${tokensToCss()}
*{box-sizing:border-box}
body{margin:0;background:var(--vs-bg);color:var(--vs-ink);
  font-family:var(--vs-font-text);font-size:var(--vs-body);
  -webkit-font-smoothing:antialiased}
main{max-width:960px;margin:0 auto;padding:var(--vs-chapter) var(--vs-gutter)}
h1{font-family:var(--vs-font-display);font-size:var(--vs-h1);font-weight:650;
  letter-spacing:-0.01em;margin:0 0 calc(var(--vs-unit)*2)}
p.lede{color:var(--vs-ink-dim);max-width:60ch;margin:0 0 calc(var(--vs-unit)*6);
  line-height:1.6}
ul{list-style:none;margin:0;padding:0;display:grid;gap:1px;
  background:var(--vs-rule);border:1px solid var(--vs-rule);border-radius:var(--vs-radius);
  overflow:hidden}
li{background:var(--vs-surface)}
a.card{display:block;padding:calc(var(--vs-unit)*3) calc(var(--vs-unit)*4);
  text-decoration:none;color:inherit}
a.card:hover{background:var(--vs-surface-raised)}
a.card:hover .card__title{color:var(--vs-accent)}
.card__title{font-family:var(--vs-font-display);font-size:var(--vs-h2);
  font-weight:650;margin:0 0 calc(var(--vs-unit)*1);transition:color 120ms}
.card__note{color:var(--vs-ink-dim);font-size:var(--vs-micro);line-height:1.6;margin:0}
.card__file{font-family:var(--vs-font-mono);font-size:var(--vs-micro);
  color:var(--vs-ink-faint);margin:calc(var(--vs-unit)*1) 0 0}
footer{margin-top:calc(var(--vs-unit)*6);color:var(--vs-ink-faint);font-size:var(--vs-micro)}
`;

  const items = entries.map(({ id, title, file }) => `<li><a class="card" href="${esc(file)}">
<p class="card__title">${esc(title)}</p>
<p class="card__note">${esc(DESCRIPTIONS[id] || '')}</p>
<p class="card__file">${esc(file)}</p>
</a></li>`).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Value Story — Demo Gallery</title>
<style>${styles}</style>
</head>
<body>
<main>
<h1>Value Story demo gallery</h1>
<p class="lede">Every rendered artifact in this gallery is generated by <code>scripts/build-gallery.mjs</code>
from a fixture in <code>fixtures/demo/</code> (plus the canonical <code>fixtures/example.value-case.json</code>).
Each link opens a self-contained HTML narrative rendered by the same renderer leadership sees.</p>
<ul>
${items}
</ul>
<footer>Generated deterministically by <code>npm run build:gallery</code>. No external references.</footer>
</main>
</body>
</html>
`;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const fixtures = listFixtures();
  const entries = [];

  for (const { id, src } of fixtures) {
    const doc = JSON.parse(readFileSync(src, 'utf8'));
    const outFile = `${id}.html`;
    const outPath = path.join(OUT_DIR, outFile);
    const receipt = deliverCase(doc, outPath);
    if (!receipt.ok) {
      process.stderr.write(`build-gallery: ${src} failed validation:\n${JSON.stringify(receipt.diagnostics, null, 2)}\n`);
      process.exit(1);
    }
    entries.push({ id, title: doc.meta?.title || doc.initiative?.name || id, file: outFile });
    process.stdout.write(`${outPath}\n`);
  }

  const indexHtml = buildIndex(entries);
  const indexPath = path.join(OUT_DIR, 'index.html');
  writeFileSync(indexPath, indexHtml, 'utf8');
  process.stdout.write(`${indexPath}\n`);
}

main();
